// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbxwcjkjqlxnujlweupf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJieHdjamtqcWx4bnVqbHdldXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzgxMDIsImV4cCI6MjA3MjY1NDEwMn0.KIcYk0ad6Z2sra-tcAvr7LP3uNL3dKQF0AyzhMkAEKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});